### ISSUE TITLE
Deze directory bevat geen video's (This directory doesn't contain any videos)

### ISSUE THREAD

**Issue by GerritHoekstra** [plexinc-plugins/Dumpert.bundle#1]
It seems that [Dumpert.nl](http://www.dumpert.nl/) changed his website.

For example [this](http://www.dumpert.nl/mediabase/6653533/99f9673f/ondertussen_in_portland.html) video. In the source code: 
```html
<div class="videoplayer" id="video1" data-files="eyJlbWJlZCI6InlvdXR1YmU6WjhDUXVBaVRlc3MiLCJzdGlsbCI6Imh0dHA6XC9cL3N0YXRpYy5kdW1wZXJ0Lm5sXC9zdGlsbHNcLzY2NTM1MzNfOTlmOTY3M2YuanBnIn0="></div>
```
Base 64 decode:
```json
{"embed":"youtube:Z8CQuAiTess","still":"http:\/\/static.dumpert.nl\/stills\/6653533_99f9673f.jpg"}
```

As you can see this is a embed video from Youtube.

Lets try a other video (for example [this](http://www.dumpert.nl/mediabase/6640150/01c7955b/waar_heeft_u_dat_gekocht_.html) video). Source code:
```html
<div class="videoplayer" id="video1" data-files="eyJmbHYiOiJodHRwOlwvXC9tZWRpYS5kdW1wZXJ0Lm5sXC9mbHZcLzAxYzc5NTViX1lURExfMS5tcDQuZmx2IiwidGFibGV0IjoiaHR0cDpcL1wvbWVkaWEuZHVtcGVydC5ubFwvdGFibGV0XC8wMWM3OTU1Yl9ZVERMXzEubXA0Lm1wNCIsIm1vYmlsZSI6Imh0dHA6XC9cL21lZGlhLmR1bXBlcnQubmxcL21vYmlsZVwvMDFjNzk1NWJfWVRETF8xLm1wNC5tcDQiLCI3MjBwIjoiaHR0cDpcL1wvbWVkaWEuZHVtcGVydC5ubFwvNzIwcFwvMDFjNzk1NWJfWVRETF8xLm1wNC5tcDQiLCJzdGlsbCI6Imh0dHA6XC9cL3N0YXRpYy5kdW1wZXJ0Lm5sXC9zdGlsbHNcLzY2NDAxNTBfMDFjNzk1NWIuanBnIn0="></div>
```

Base 64 decode:
```json
{"flv":"http:\/\/media.dumpert.nl\/flv\/01c7955b_YTDL_1.mp4.flv","tablet":"http:\/\/media.dumpert.nl\/tablet\/01c7955b_YTDL_1.mp4.mp4","mobile":"http:\/\/media.dumpert.nl\/mobile\/01c7955b_YTDL_1.mp4.mp4","720p":"http:\/\/media.dumpert.nl\/720p\/01c7955b_YTDL_1.mp4.mp4","still":"http:\/\/static.dumpert.nl\/stills\/6640150_01c7955b.jpg"}
```

This video is not embedded but was directly uploaded to the website.

I hope it's possible to rewrite the plugin to this schema.

**Comment by sander1** [comment]
Fixes in https://github.com/plexinc-plugins/Dumpert.bundle/commit/c21f6a1f37e4c11ec96d899c794e29575615c4cd en https://github.com/plexinc-plugins/Services.bundle/commit/c54d19b6df065c06841cef34fa4a72486036c881 zouden het kanaal weer moeten laten werken.
